title: Matheus Rodrigues
name: Matheus
email: matheusrf96@gmail.com
description: Web Developer

baseurl: "/"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/code2.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/twoscreen.jpg

project_one: Helpdesk - Câmara Municipal de Três Corações
project_one_description: Um helpdesk para atender as necessidades da Câmara Municipal da cidade de Três Corações - MG
project_one_url: https://github.com/camaratc/helpdesk_django
project_one_icon: location_on
project_one_img: assets/images/projects/helpdesk.png

project_two: Second Project
project_two_description: Describe your project!
project_two_url: https://github.com/jameshamann/jekyll-material-theme
project_two_icon: photo_camera
project_two_img: assets/images/projects/02.png

project_three: Third Project
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel
project_three_img: assets/images/projects/03.png

project_four: Fourth Project
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant
project_four_img: assets/images/projects/04.png

portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: angularjs
#  - name: apache
  - name: atom
  - name: bitbucket
  - name: bootstrap
  - name: coffescript
  - name: css3
  - name: django
  - name: docker
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: heroku
  - name: html5
  - name: inkscape
  - name: java
  - name: javascript
#  - name: laravel
  - name: less
  - name: linux
#  - name: meteor
  - name: mongodb
  - name: mysql
#  - name: nginx
  - name: nodejs
  - name: php
  - name: postgresql
  - name: python
  - name: rails
#  - name: react
  - name: ruby
  - name: sass
  - name: ssh
  - name: trello
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: windows8
  - name: wordpress

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/matheusrf96
# medium: https://medium.com

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.
cookie_accept_message: Obrigado!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
